name: "Main action file of Docker container actions"
description: "Docker container actions"
inputs:
  GITHUB_TOKEN:
    description: "Token used to access repo"
    required: false
  repo:
    description: repository name
    default: ${{ github.repository }}
    required: false 
  pr_number:
    description: PR number
    required: false
  merge_pr:
    description: PR number
    required: false
  close_pr:
    description: PR number
    required: false  

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    REPO_OWNER: ${{ inputs.owner }}
    REPO_NAME: ${{ inputs.repo }}

