name: Close PR Without Description or Targeted to Master

on:
  pull_request:
    types: [opened, edited,reopened]

permissions: write-all
env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    REPO_NAME: ${{github.repository}}
jobs:
  close_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Merge and close PR
        uses: ./