name: Close PR Without Description or Targeted to Master

on:
  pull_request:
    types: [opened, edited]

jobs:
  close_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check PR description and target branch
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            PR_DESCRIPTION=$(jq -r .pull_request.body $GITHUB_EVENT_PATH)
            PR_BASE_BRANCH=$(jq -r .pull_request.base.ref $GITHUB_EVENT_PATH)
            
            if [[ -z "$PR_DESCRIPTION" ]]; then
              echo "Closing PR because it has no description."
              curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge -d '{"state":"closed"}'
              exit 0
            fi
            
            if [[ "$PR_BASE_BRANCH" == 'master' ]]; then
              IS_RELEASE_BRANCH=$(echo "$PR_DESCRIPTION" | grep -E '^release/.*$')
              if [[ -z "$IS_RELEASE_BRANCH" ]]; then
                echo "Closing PR because it targets directly to the master branch."
                curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge -d '{"state":"closed"}'
                exit 0
              fi
            fi
          fi