name: Issue Comment Workflow

on:
  issue_comment:
    types: [created, edited, deleted]
    branches:
        - '*'

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Issue comment event occurred!"