name: check github action
on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@3
        - name: Testing bash script
          run: |
               echo "print hello"
               ls
               uname


